name: GitHub Pages

on:
  push:
    branches: [ main ]
jobs:
  depoy:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install
      run: npm ci
    - name: Build and Deploy
      env:
        NODE_ENV: production
        # Remove this line if you would like to skip using google analytics
        REACT_APP_GA_TRACKING_ID: UA-68649021-1
        # This is set automatically by github
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
          git config user.name "iflymissions"
          git config user.email "iflymissions@gmail.com" #actions@users.noreply.github.com
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/iflymissions/missions.git
          npm run deploy
